// This file is a placeholder.
// The actual service worker will be automatically generated by the build process
// using 'vite-plugin-pwa' configured in vite.config.ts.
// When you run 'npm run build', a complete sw.js will be created in the dist/ folder.
